print("Hello")
print('Hello')
print("It's alright")
print("He is called 'Johnny'")
print('He is called "Johnny"')
a = "Hello"
print(a)
B = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(B)
a = "Hello, World!"
print(a[1])
#TO GET THE LENGTH OF THE STRING
C = "Hello, World!"
print(len(C))
txt = "The best things in life are free!"
print("free" in txt)
txt = "Aashu is the best"
print("Aashu" in txt)

b = "Hello, World!"
print(b[-5:-2])

